from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.artifact import Artifact
    from app.models.user import User


# Author role values
ROLE_STUDENT = "student"
ROLE_TEACHER = "teacher"
ROLE_AI = "ai"

# Remark kind values
KIND_COMMENT = "comment"          # a human note
KIND_CRITIQUE = "critique"        # an AI critique of a field
KIND_APPROVAL = "approval"        # a human approval of a field


class Remark(Base, UUIDMixin, TimestampMixin):
    """
    A comment, critique, or approval anchored to a specific field
    of a specific artifact.

    `field_path` uses dot notation to address nested fields:
      - "problem"                  — top-level field
      - "tasks.0.duration"         — nested array element
      - "nodes.db1.tech_stack"     — nested object key

    When author_role is "ai", the remark was generated by the AI Mentor.
    When "teacher", a human teacher wrote it. When "student", the
    project's owner or a peer in the same tenant wrote it.

    AI remarks have no author_id (the system generates them).
    """
    __tablename__ = "remarks"

    tenant_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    project_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    artifact_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("artifacts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    author_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,   # null for AI remarks
        index=True,
    )

    field_path: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    author_role: Mapped[str] = mapped_column(String(50), nullable=False)
    kind: Mapped[str] = mapped_column(
        String(50), nullable=False, default=KIND_COMMENT, server_default=KIND_COMMENT
    )

    artifact: Mapped["Artifact"] = relationship(
        "Artifact", back_populates="remarks"
    )
    author: Mapped["User | None"] = relationship("User")

    def __repr__(self) -> str:
        return (
            f"<Remark on {self.field_path} by "
            f"{self.author_role or 'unknown'}>"
        )
