"""add_peer_validations.py

Revision ID: 09b56ad0190d
Revises: eef6034bf1f3
Create Date: 2026-09-22 11:04:24.261884

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '09b56ad0190d'
down_revision: Union[str, None] = 'eef6034bf1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_is_current'), 'artifacts', ['is_current'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_phase'), 'artifacts', ['phase'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    op.create_index('uq_artifacts_project_kind_current', 'artifacts', ['project_id', 'kind'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('gate_evaluations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_by', sa.UUID(), nullable=True),
    sa.Column('gate', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('missing', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ai_feedback', sa.String(length=2000), nullable=True),
    sa.Column('peer_validation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_evaluations_gate'), 'gate_evaluations', ['gate'], unique=False)
    op.create_index(op.f('ix_gate_evaluations_project_id'), 'gate_evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_gate_evaluations_tenant_id'), 'gate_evaluations', ['tenant_id'], unique=False)
    op.create_table('remarks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), server_default='comment', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remarks_artifact_id'), 'remarks', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_remarks_author_id'), 'remarks', ['author_id'], unique=False)
    op.create_index(op.f('ix_remarks_field_path'), 'remarks', ['field_path'], unique=False)
    op.create_index(op.f('ix_remarks_project_id'), 'remarks', ['project_id'], unique=False)
    op.create_index(op.f('ix_remarks_tenant_id'), 'remarks', ['tenant_id'], unique=False)
    op.drop_constraint('uq_peer_validations_project_validator', 'peer_validations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_peer_validations_project_validator', 'peer_validations', ['project_id', 'validator_id', 'phase'])
    op.drop_index(op.f('ix_remarks_tenant_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_project_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_field_path'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_author_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_artifact_id'), table_name='remarks')
    op.drop_table('remarks')
    op.drop_index(op.f('ix_gate_evaluations_tenant_id'), table_name='gate_evaluations')
    op.drop_index(op.f('ix_gate_evaluations_project_id'), table_name='gate_evaluations')
    op.drop_index(op.f('ix_gate_evaluations_gate'), table_name='gate_evaluations')
    op.drop_table('gate_evaluations')
    op.drop_index('uq_artifacts_project_kind_current', table_name='artifacts', postgresql_where=sa.text('is_current = true'))
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_phase'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_is_current'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
