"""add_github_oauth_fields

Revision ID: 20aeb3377551
Revises: c527e91076e8
Create Date: 2026-09-23 03:46:58.473526

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20aeb3377551'
down_revision: Union[str, None] = 'c527e91076e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('github_token_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_connected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_connected_at')
    op.drop_column('users', 'github_token_encrypted')
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
