"""finish_artifacts_migration

Revision ID: 64a5641b1058
Revises: 09b56ad0190d
Create Date: 2026-09-22 11:06:39.771096

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '64a5641b1058'
down_revision: Union[str, None] = '09b56ad0190d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_peer_validations_project_validator', 'peer_validations', ['project_id', 'validator_id', 'phase'])
    # ### end Alembic commands ###
    # ─── Data migration: phase_data → artifacts ───
    op.execute("""
        INSERT INTO artifacts (
            id, tenant_id, project_id, phase, kind, data,
            version, is_current, created_at, updated_at
        )
        SELECT
            gen_random_uuid(),
            tenant_id,
            id,
            'idea',
            'lean_canvas',
            phase_data,
            1,
            true,
            NOW(),
            NOW()
        FROM projects
        WHERE phase_data != '{}'::jsonb
          AND NOT EXISTS (
              SELECT 1 FROM artifacts a
              WHERE a.project_id = projects.id
                AND a.kind = 'lean_canvas'
          )
    """)

    op.drop_column("projects", "phase_data")


def downgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "phase_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )

    op.execute("""
        UPDATE projects p
        SET phase_data = a.data
        FROM artifacts a
        WHERE a.project_id = p.id
          AND a.kind = 'lean_canvas'
          AND a.is_current = true
    """)

    op.drop_constraint(
        "uq_peer_validations_project_validator",
        "peer_validations",
        type_="unique",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_peer_validations_project_validator', 'peer_validations', type_='unique')
    # ### end Alembic commands ###
