"""add_scaffolds

Revision ID: c527e91076e8
Revises: 9c89f6442047
Create Date: 2026-09-22 21:58:08.850640

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c527e91076e8'
down_revision: Union[str, None] = '9c89f6442047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scaffold_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('repo_full_name', sa.String(length=200), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scaffold_jobs_project_id'), 'scaffold_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_scaffold_jobs_tenant_id'), 'scaffold_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scaffold_jobs_tenant_id'), table_name='scaffold_jobs')
    op.drop_index(op.f('ix_scaffold_jobs_project_id'), table_name='scaffold_jobs')
    op.drop_table('scaffold_jobs')
    # ### end Alembic commands ###
