"""add_peer_validations

Revision ID: eef6034bf1f3
Revises: e334d224b1df
Create Date: 2026-09-22 07:41:40.544922

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eef6034bf1f3'
down_revision: Union[str, None] = 'e334d224b1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_validations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('validator_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=50), server_default='idea', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_validations_project_id'), 'peer_validations', ['project_id'], unique=False)
    op.create_index(op.f('ix_peer_validations_tenant_id'), 'peer_validations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_peer_validations_validator_id'), 'peer_validations', ['validator_id'], unique=False)
    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    op.create_unique_constraint(
        "uq_peer_validations_project_validator",
        "peer_validations",
        ["project_id", "validator_id", "phase"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "uq_peer_validations_project_validator",
        "peer_validations",
        type_="unique",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])
    op.drop_index(op.f('ix_peer_validations_validator_id'), table_name='peer_validations')
    op.drop_index(op.f('ix_peer_validations_tenant_id'), table_name='peer_validations')
    op.drop_index(op.f('ix_peer_validations_project_id'), table_name='peer_validations')
    op.drop_table('peer_validations')
    # ### end Alembic commands ###
