"""
Deploy script generator.

One template per deployment target. Produces a shell script the
student can run from their laptop (or in Codespaces).
"""
from typing import Literal


TargetId = Literal[
    "railway", "fly", "vercel", "docker", "codespaces", "custom",
    "github_pages", "npm", "pypi", "chrome_store", "local_network", "download",
]


def _header(project_name, target):
    return chr(10).join([
        "#!/usr/bin/env bash",
        "# Deploy script for " + project_name,
        "# Target: " + target,
        "# Generated by SOJIP",
        "",
        "set -euo pipefail",
        "",
    ])


def _env_block(env_keys):
    if not env_keys:
        return "# --- Environment ---" + chr(10) + "# No env vars configured." + chr(10) + chr(10)
    lines = [
        "# --- Environment ---",
        "# This script sources a local .env file.",
        "# Create one (gitignored) with these keys:",
        "#",
    ]
    for k in env_keys:
        lines.append("#   " + k + "=<your value>")
    lines.extend([
        "#",
        "if [ ! -f .env ]; then",
        "  echo 'Error: .env not found.' >&2",
        "  exit 1",
        "fi",
        "set -a",
        ". ./.env",
        "set +a",
        "",
    ])
    return chr(10).join(lines)


# --- Full-stack targets ---

def _railway_body(slug):
    return chr(10).join([
        "# --- Railway ---",
        "if ! command -v railway > /dev/null; then npm i -g @railway/cli; fi",
        "railway login",
        "railway link",
        "railway up",
        "echo 'Get URL: railway domain'",
        "",
    ])


def _fly_body(slug):
    return chr(10).join([
        "# --- Fly.io ---",
        "if ! command -v flyctl > /dev/null; then",
        "  curl -L https://fly.io/install.sh | sh",
        "  export PATH=\"$HOME/.fly/bin:$PATH\"",
        "fi",
        "flyctl auth login",
        "if [ ! -f fly.toml ]; then flyctl launch --name " + slug + " --no-deploy; fi",
        "flyctl deploy",
        "echo 'Get URL: flyctl status'",
        "",
    ])


def _vercel_body(slug):
    return chr(10).join([
        "# --- Vercel ---",
        "if ! command -v vercel > /dev/null; then npm i -g vercel; fi",
        "vercel login",
        "vercel --prod",
        "echo 'Vercel prints the URL above.'",
        "",
    ])


def _docker_body(slug):
    return chr(10).join([
        "# --- Docker ---",
        "IMAGE='" + slug + ":latest'",
        "docker build -t \"$IMAGE\" .",
        "echo 'Run: docker run --env-file .env -p 8000:8000 $IMAGE'",
        "",
    ])


def _codespaces_body(slug):
    return chr(10).join([
        "# --- Codespaces ---",
        "echo 'Starting dev server...'",
        "echo 'Codespaces will show the URL in the PORTS tab.'",
        "if [ -f package.json ]; then npm run dev;",
        "elif [ -f requirements.txt ]; then uvicorn app.main:app --host 0.0.0.0 --port 8000;",
        "else echo 'Edit this script to start your server.'; fi",
        "",
    ])


def _custom_body(slug):
    return chr(10).join([
        "# --- Custom ---",
        "echo 'TODO: replace with your deploy commands.'",
        "",
    ])


# --- Standalone targets ---

def _github_pages_body(slug):
    return chr(10).join([
        "# --- GitHub Pages ---",
        "if ! command -v gh-pages > /dev/null; then npm i -g gh-pages; fi",
        "SOURCE_DIR='.'",
        "if [ -d './dist' ]; then SOURCE_DIR='./dist'; fi",
        "if [ -d './build' ]; then SOURCE_DIR='./build'; fi",
        "gh-pages -d \"$SOURCE_DIR\"",
        "echo 'Your URL: https://<username>.github.io/" + slug + "'",
        "",
    ])


def _npm_body(slug):
    return chr(10).join([
        "# --- npm registry ---",
        "npm whoami || npm login",
        "npm publish",
        "echo 'Verify: https://www.npmjs.com/package/<name>'",
        "",
    ])


def _pypi_body(slug):
    pkg = slug.replace("-", "_")
    return chr(10).join([
        "# --- PyPI ---",
        "PY=$(command -v python3 || command -v python)",
        "$PY -m pip install --upgrade pip build twine",
        "$PY -m build",
        "$PY -m twine upload dist/*",
        "echo 'Verify: https://pypi.org/project/" + pkg + "/'",
        "",
    ])


def _chrome_store_body(slug):
    return chr(10).join([
        "# --- Chrome Web Store ---",
        "BUNDLE='" + slug + "-extension.zip'",
        "rm -f \"$BUNDLE\"",
        "zip -r \"$BUNDLE\" . -x '*.git*' '*.zip'",
        "echo 'Bundle: $BUNDLE'",
        "echo 'Upload at: https://chrome.google.com/webstore/devconsole'",
        "",
    ])


def _local_network_body(slug):
    return chr(10).join([
        "# --- Local network ---",
        "echo 'Detecting local IP...'",
        "if command -v ip > /dev/null; then ip -4 addr show | grep inet; fi",
        "echo 'Starting service on 0.0.0.0...'",
        "if [ -f app.py ]; then python app.py; fi",
        "",
    ])


def _download_body(slug):
    return chr(10).join([
        "# --- GitHub release ---",
        "if ! command -v gh > /dev/null; then",
        "  echo 'Install gh: https://cli.github.com/'",
        "  exit 1",
        "fi",
        "VERSION=${1:-v1.0.0}",
        "gh release create \"$VERSION\" --title \"$VERSION\" --notes 'Release $VERSION'",
        "echo 'Release created.'",
        "",
    ])


# --- Registry ---

_TARGET_BODIES = {
    "railway": _railway_body,
    "fly": _fly_body,
    "vercel": _vercel_body,
    "docker": _docker_body,
    "codespaces": _codespaces_body,
    "custom": _custom_body,
    "github_pages": _github_pages_body,
    "npm": _npm_body,
    "pypi": _pypi_body,
    "chrome_store": _chrome_store_body,
    "local_network": _local_network_body,
    "download": _download_body,
}


def generate_deploy_script(target, project_name, project_slug, env_keys):
    body_fn = _TARGET_BODIES.get(target, _custom_body)
    return _header(project_name, target) + chr(10) + _env_block(env_keys) + body_fn(project_slug)


def generate_env_example(env_keys):
    if not env_keys:
        return "# No env vars defined yet." + chr(10)
    parts = [
        "# Environment variables for this project.",
        "# Copy to .env and fill in real values.",
        "",
    ]
    for k in sorted(env_keys):
        parts.append(k + "=")
    return chr(10).join(parts) + chr(10)
