"""
Starter files for each scaffold template.

Each template maps to a dict: { path: file_content }.

Content is stored as plain Python strings. Keep files short and
useful — students should be able to read every line.
"""


TEMPLATE_FILES: dict[str, dict[str, str]] = {
    "nextjs-fastapi": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP - Seed . Offspring . Journey . Innovation . Platform.\n"
            "\n"
            "## Tech stack\n"
            "\n"
            "- **Frontend:** Next.js 14 (App Router)\n"
            "- **Backend:** FastAPI (Python 3.11)\n"
            "- **Database:** PostgreSQL\n"
            "- **Deployment:** Docker Compose\n"
            "\n"
            "## Getting started\n"
            "\n"
            "```bash\n"
            "docker compose up\n"
            "```\n"
            "\n"
            "Then open http://localhost:3000.\n"
            "\n"
            "## Structure\n"
            "\n"
            "- `frontend/` - Next.js application\n"
            "- `backend/` - FastAPI application\n"
            "- `docker-compose.yml` - local dev environment\n"
        ),
        ".gitignore": (
            "# Node\n"
            "node_modules/\n"
            ".next/\n"
            "out/\n"
            "\n"
            "# Python\n"
            "__pycache__/\n"
            "*.pyc\n"
            ".venv/\n"
            "venv/\n"
            "\n"
            "# Environment\n"
            ".env\n"
            ".env.local\n"
            "\n"
            "# OS\n"
            ".DS_Store\n"
            "\n"
            "# IDE\n"
            ".vscode/\n"
            ".idea/\n"
        ),
        "docker-compose.yml": (
            "version: '3.8'\n"
            "\n"
            "services:\n"
            "  postgres:\n"
            "    image: postgres:15-alpine\n"
            "    environment:\n"
            "      POSTGRES_USER: app\n"
            "      POSTGRES_PASSWORD: dev\n"
            "      POSTGRES_DB: {project_slug}\n"
            "    ports:\n"
            '      - "5432:5432"\n'
            "    volumes:\n"
            "      - postgres_data:/var/lib/postgresql/data\n"
            "\n"
            "  backend:\n"
            "    build: ./backend\n"
            "    environment:\n"
            "      DATABASE_URL: postgresql://app:dev@postgres:5432/{project_slug}\n"
            "    ports:\n"
            '      - "8000:8000"\n'
            "    depends_on:\n"
            "      - postgres\n"
            "    volumes:\n"
            "      - ./backend:/app\n"
            "\n"
            "  frontend:\n"
            "    build: ./frontend\n"
            "    environment:\n"
            "      NEXT_PUBLIC_API_URL: http://localhost:8000\n"
            "    ports:\n"
            '      - "3000:3000"\n'
            "    depends_on:\n"
            "      - backend\n"
            "    volumes:\n"
            "      - ./frontend:/app\n"
            "      - /app/node_modules\n"
            "\n"
            "volumes:\n"
            "  postgres_data:\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on:\n"
            "  push:\n"
            "    branches: [main]\n"
            "  pull_request:\n"
            "    branches: [main]\n"
            "\n"
            "jobs:\n"
            "  backend:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
            "      - run: pip install -r backend/requirements.txt\n"
            "      - run: cd backend && python -c 'import app'\n"
            "\n"
            "  frontend:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-node@v4\n"
            "        with:\n"
            "          node-version: '20'\n"
            "      - run: cd frontend && npm install\n"
            "      - run: cd frontend && npm run build\n"
        ),
    },

    "nextjs-node": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Tech stack\n"
            "\n"
            "- **Frontend:** Next.js 14\n"
            "- **Backend:** Node.js (Express)\n"
            "- **Database:** PostgreSQL (Prisma)\n"
            "\n"
            "## Getting started\n"
            "\n"
            "```bash\n"
            "npm install\n"
            "npx prisma migrate dev\n"
            "npm run dev\n"
            "```\n"
        ),
        ".gitignore": (
            "node_modules/\n"
            ".next/\n"
            "dist/\n"
            ".env\n"
            ".env.local\n"
            ".DS_Store\n"
        ),
        "docker-compose.yml": (
            "version: '3.8'\n"
            "\n"
            "services:\n"
            "  postgres:\n"
            "    image: postgres:15-alpine\n"
            "    environment:\n"
            "      POSTGRES_USER: app\n"
            "      POSTGRES_PASSWORD: dev\n"
            "      POSTGRES_DB: {project_slug}\n"
            "    ports:\n"
            '      - "5432:5432"\n'
            "    volumes:\n"
            "      - postgres_data:/var/lib/postgresql/data\n"
            "\n"
            "volumes:\n"
            "  postgres_data:\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on: [push, pull_request]\n"
            "\n"
            "jobs:\n"
            "  build:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-node@v4\n"
            "        with:\n"
            "          node-version: '20'\n"
            "      - run: npm install\n"
            "      - run: npm run build\n"
        ),
    },

    "react-python": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Tech stack\n"
            "\n"
            "- **Frontend:** React\n"
            "- **Backend:** Python (Flask + Pandas)\n"
            "- **Database:** SQLite (for prototyping)\n"
            "\n"
            "## Getting started\n"
            "\n"
            "```bash\n"
            "cd backend && pip install -r requirements.txt && python app.py\n"
            "cd frontend && npm install && npm start\n"
            "```\n"
        ),
        ".gitignore": (
            "node_modules/\n"
            "__pycache__/\n"
            "*.pyc\n"
            ".env\n"
            ".DS_Store\n"
        ),
        "docker-compose.yml": (
            "version: '3.8'\n"
            "\n"
            "services:\n"
            "  backend:\n"
            "    build: ./backend\n"
            "    ports:\n"
            '      - "5000:5000"\n'
            "    volumes:\n"
            "      - ./backend:/app\n"
            "\n"
            "  frontend:\n"
            "    build: ./frontend\n"
            "    ports:\n"
            '      - "3000:3000"\n'
            "    depends_on:\n"
            "      - backend\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on: [push, pull_request]\n"
            "\n"
            "jobs:\n"
            "  backend:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
            "      - run: pip install -r backend/requirements.txt\n"
            "\n"
            "  frontend:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-node@v4\n"
            "        with:\n"
            "          node-version: '20'\n"
            "      - run: cd frontend && npm install\n"
        ),
    },

    "python-only": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Tech stack\n"
            "\n"
            "- Python 3.11\n"
            "- pytest\n"
            "\n"
            "## Getting started\n"
            "\n"
            "```bash\n"
            "pip install -r requirements.txt\n"
            "python -m {project_slug}\n"
            "```\n"
        ),
        ".gitignore": (
            "__pycache__/\n"
            "*.pyc\n"
            ".venv/\n"
            "venv/\n"
            ".env\n"
            ".DS_Store\n"
            ".pytest_cache/\n"
        ),
        "requirements.txt": (
            "pytest==8.0.0\n"
            "ruff==0.2.0\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on: [push, pull_request]\n"
            "\n"
            "jobs:\n"
            "  test:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
            "      - run: pip install -r requirements.txt\n"
            "      - run: pytest\n"
        ),
    },

    "r-shiny": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Tech stack\n"
            "\n"
            "- R 4.3\n"
            "- Shiny\n"
            "- ggplot2\n"
            "\n"
            "## Getting started\n"
            "\n"
            "```r\n"
            'install.packages("renv")\n'
            "renv::restore()\n"
            "shiny::runApp()\n"
            "```\n"
        ),
        ".gitignore": (
            ".Rproj.user\n"
            ".Rhistory\n"
            ".RData\n"
            ".Ruserdata\n"
            "renv/library/\n"
            ".env\n"
        ),
        "app.R": (
            "library(shiny)\n"
            "\n"
            "ui <- fluidPage(\n"
            '  titlePanel("{project_name}"),\n'
            "  sidebarLayout(\n"
            "    sidebarPanel(\n"
            '      sliderInput("n", "Number of points:", 10, 500, 100)\n'
            "    ),\n"
            "    mainPanel(\n"
            '      plotOutput("plot")\n'
            "    )\n"
            "  )\n"
            ")\n"
            "\n"
            "server <- function(input, output) {\n"
            '  output$plot <- renderPlot({\n'
            '    plot(rnorm(input$n), main = "{project_name}")\n'
            "  })\n"
            "}\n"
            "\n"
            "shinyApp(ui = ui, server = server)\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on: [push, pull_request]\n"
            "\n"
            "jobs:\n"
            "  check:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - uses: r-lib/actions/setup-r@v2\n"
            '      - run: Rscript -e "print(\'ok\')"\n'
        ),
    },

    "static-site": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Getting started\n"
            "\n"
            "Open `index.html` in a browser - no build step needed.\n"
        ),
        ".gitignore": ".DS_Store\n.env\n",
        "index.html": (
            "<!DOCTYPE html>\n"
            '<html lang="en">\n'
            "<head>\n"
            '    <meta charset="UTF-8">\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
            "    <title>{project_name}</title>\n"
            '    <link rel="stylesheet" href="style.css">\n'
            "</head>\n"
            "<body>\n"
            "    <main>\n"
            "        <h1>{project_name}</h1>\n"
            "        <p>{description}</p>\n"
            "    </main>\n"
            '    <script src="script.js"></script>\n'
            "</body>\n"
            "</html>\n"
        ),
        ".github/workflows/main.yml": (
            "name: CI\n"
            "\n"
            "on: [push, pull_request]\n"
            "\n"
            "jobs:\n"
            "  validate:\n"
            "    runs-on: ubuntu-latest\n"
            "    steps:\n"
            "      - uses: actions/checkout@v4\n"
            "      - name: Check HTML exists\n"
            "        run: test -f index.html\n"
        ),
    },

    # ─── Standalone App Templates ─────────────────────────

    "single-html": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "Generated by SOJIP.\n"
            "\n"
            "## Getting started\n"
            "\n"
            "Open `index.html` in a browser. That's it.\n"
            "\n"
            "## Deploying\n"
            "\n"
            "Run the deploy script from SOJIP to publish this to GitHub Pages.\n"
        ),
        "index.html": (
            "<!DOCTYPE html>\n"
            "<html lang=\"en\">\n"
            "<head>\n"
            "    <meta charset=\"UTF-8\">\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            "    <title>{project_name}</title>\n"
            "    <style>\n"
            "        body {\n"
            "            font-family: system-ui, -apple-system, sans-serif;\n"
            "            max-width: 720px;\n"
            "            margin: 80px auto;\n"
            "            padding: 0 24px;\n"
            "            color: #1e293b;\n"
            "            line-height: 1.6;\n"
            "        }\n"
            "        h1 { color: #c85a3a; }\n"
            "    </style>\n"
            "</head>\n"
            "<body>\n"
            "    <h1>{project_name}</h1>\n"
            "    <p>{description}</p>\n"
            "    <p>Edit <code>index.html</code> to start building.</p>\n"
            "</body>\n"
            "</html>\n"
        ),
        ".gitignore": ".DS_Store\n.env\n",
    },

    "chrome-extension": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "A Chrome extension (Manifest V3).\n"
            "\n"
            "## Installing locally\n"
            "\n"
            "1. Open `chrome://extensions` in Chrome\n"
            "2. Enable **Developer mode** (top right)\n"
            "3. Click **Load unpacked** and select this folder\n"
            "\n"
            "## Publishing\n"
            "\n"
            "Run the deploy script from SOJIP to create the store bundle.\n"
        ),
        "manifest.json": (
            "{\n"
            "    \"manifest_version\": 3,\n"
            "    \"name\": \"{project_name}\",\n"
            "    \"version\": \"0.1.0\",\n"
            "    \"description\": \"{description}\",\n"
            "    \"action\": {\n"
            "        \"default_popup\": \"popup.html\",\n"
            "        \"default_title\": \"{project_name}\"\n"
            "    },\n"
            "    \"permissions\": [],\n"
            "    \"host_permissions\": []\n"
            "}\n"
        ),
        "popup.html": (
            "<!DOCTYPE html>\n"
            "<html>\n"
            "<head>\n"
            "    <meta charset=\"utf-8\">\n"
            "    <style>\n"
            "        body { width: 300px; padding: 16px; font-family: system-ui; }\n"
            "        h1 { font-size: 16px; margin: 0 0 8px; color: #c85a3a; }\n"
            "    </style>\n"
            "</head>\n"
            "<body>\n"
            "    <h1>{project_name}</h1>\n"
            "    <p>Popup content goes here.</p>\n"
            "    <script src=\"popup.js\"></script>\n"
            "</body>\n"
            "</html>\n"
        ),
        "popup.js": "console.log(\"{project_name} popup loaded\");\n",
        ".gitignore": ".DS_Store\n*.zip\n",
    },

    "cli-python": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "A Python CLI. Install with `pip install -e .` and run:\n"
            "\n"
            "```bash\n"
            "{project_slug} --help\n"
            "```\n"
            "\n"
            "## Publishing to PyPI\n"
            "\n"
            "Run the deploy script from SOJIP.\n"
        ),
        "pyproject.toml": (
            "[build-system]\n"
            "requires = [\"setuptools>=68\", \"wheel\"]\n"
            "build-backend = \"setuptools.build_meta\"\n"
            "\n"
            "[project]\n"
            "name = \"{project_slug}\"\n"
            "version = \"0.1.0\"\n"
            "description = \"{description}\"\n"
            "requires-python = \">=3.10\"\n"
            "dependencies = [\"click>=8.1\"]\n"
            "\n"
            "[project.scripts]\n"
            "{project_slug} = \"{module}:main\"\n"
            "\n"
            "[tool.setuptools]\n"
            "packages = [\"{module}\"]\n"
        ),
        "requirements.txt": "click>=8.1\npytest>=8.0\nruff>=0.2.0\n",
        ".gitignore": "__pycache__/\n*.pyc\n.venv/\nvenv/\ndist/\nbuild/\n*.egg-info/\n.env\n",
    },

    "cli-node": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "An npm-publishable CLI. Install and run with:\n"
            "\n"
            "```bash\n"
            "npx {project_slug} --help\n"
            "```\n"
            "\n"
            "## Publishing to npm\n"
            "\n"
            "Run the deploy script from SOJIP.\n"
        ),
        "package.json": (
            "{\n"
            "  \"name\": \"{project_slug}\",\n"
            "  \"version\": \"0.1.0\",\n"
            "  \"description\": \"{description}\",\n"
            "  \"bin\": { \"{project_slug}\": \"./dist/index.js\" },\n"
            "  \"main\": \"./dist/index.js\",\n"
            "  \"type\": \"module\",\n"
            "  \"scripts\": {\n"
            "    \"build\": \"tsc\",\n"
            "    \"dev\": \"tsx src/index.ts\",\n"
            "    \"test\": \"echo \\\"no tests yet\\\"\"\n"
            "  },\n"
            "  \"dependencies\": {\n"
            "    \"commander\": \"^12.0.0\"\n"
            "  },\n"
            "  \"devDependencies\": {\n"
            "    \"typescript\": \"^5.3.0\",\n"
            "    \"@types/node\": \"^20.0.0\",\n"
            "    \"tsx\": \"^4.7.0\"\n"
            "  }\n"
            "}\n"
        ),
        "tsconfig.json": (
            "{\n"
            "  \"compilerOptions\": {\n"
            "    \"target\": \"ES2022\",\n"
            "    \"module\": \"NodeNext\",\n"
            "    \"moduleResolution\": \"NodeNext\",\n"
            "    \"outDir\": \"./dist\",\n"
            "    \"rootDir\": \"./src\",\n"
            "    \"strict\": true,\n"
            "    \"declaration\": true,\n"
            "    \"esModuleInterop\": true\n"
            "  },\n"
            "  \"include\": [\"src/**/*\"]\n"
            "}\n"
        ),
        "src/index.ts": (
            "#!/usr/bin/env node\n"
            "import { Command } from \"commander\";\n"
            "\n"
            "const program = new Command();\n"
            "program\n"
            "  .name(\"{project_slug}\")\n"
            "  .description(\"{description}\")\n"
            "  .version(\"0.1.0\");\n"
            "\n"
            "program\n"
            "  .command(\"hello\")\n"
            "  .description(\"Say hello\")\n"
            "  .action(() => { console.log(\"Hello from {project_name}!\"); });\n"
            "\n"
            "program.parse();\n"
        ),
        ".gitignore": "node_modules/\ndist/\n.env\n.DS_Store\n",
    },

    "electron-desktop": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "A cross-platform desktop app built with Electron.\n"
            "\n"
            "## Development\n"
            "\n"
            "```bash\n"
            "npm install\n"
            "npm start\n"
            "```\n"
            "\n"
            "## Building installers\n"
            "\n"
            "```bash\n"
            "npm run make\n"
            "```\n"
            "\n"
            "Run the deploy script from SOJIP to publish a GitHub release.\n"
        ),
        "package.json": (
            "{\n"
            "  \"name\": \"{project_slug}\",\n"
            "  \"version\": \"0.1.0\",\n"
            "  \"description\": \"{description}\",\n"
            "  \"main\": \"src/index.js\",\n"
            "  \"scripts\": {\n"
            "    \"start\": \"electron .\",\n"
            "    \"make\": \"electron-forge make\"\n"
            "  },\n"
            "  \"devDependencies\": {\n"
            "    \"electron\": \"^28.0.0\",\n"
            "    \"@electron-forge/cli\": \"^7.2.0\",\n"
            "    \"@electron-forge/maker-zip\": \"^7.2.0\"\n"
            "  }\n"
            "}\n"
        ),
        "src/index.js": (
            "const { app, BrowserWindow } = require(\"electron\");\n"
            "const path = require(\"path\");\n"
            "\n"
            "function createWindow() {\n"
            "  const win = new BrowserWindow({\n"
            "    width: 900,\n"
            "    height: 700,\n"
            "    webPreferences: { contextIsolation: true }\n"
            "  });\n"
            "  win.loadFile(\"src/index.html\");\n"
            "}\n"
            "\n"
            "app.whenReady().then(createWindow);\n"
            "app.on(\"window-all-closed\", () => app.quit());\n"
        ),
        "src/index.html": (
            "<!DOCTYPE html>\n"
            "<html>\n"
            "<head>\n"
            "    <meta charset=\"utf-8\">\n"
            "    <title>{project_name}</title>\n"
            "    <style>\n"
            "        body { font-family: system-ui; padding: 40px; color: #1e293b; }\n"
            "        h1 { color: #c85a3a; }\n"
            "    </style>\n"
            "</head>\n"
            "<body>\n"
            "    <h1>{project_name}</h1>\n"
            "    <p>{description}</p>\n"
            "</body>\n"
            "</html>\n"
        ),
        ".gitignore": "node_modules/\nout/\ndist/\n.env\n.DS_Store\n",
    },

    "raspberry-pi": {
        "README.md": (
            "# {project_name}\n"
            "\n"
            "{description}\n"
            "\n"
            "A Raspberry Pi service with a systemd unit.\n"
            "\n"
            "## Install on the Pi\n"
            "\n"
            "```bash\n"
            "git clone <this repo>\n"
            "cd {project_slug}\n"
            "sudo ./install.sh\n"
            "```\n"
            "\n"
            "The service will start automatically on boot.\n"
            "\n"
            "## Check status\n"
            "\n"
            "```bash\n"
            "sudo systemctl status {project_slug}\n"
            "sudo journalctl -u {project_slug} -f\n"
            "```\n"
        ),
        "app.py": (
            "#!/usr/bin/env python3\n"
            "\"\"\"\n"
            "{project_name}\n"
            "\n"
            "A simple HTTP service that reports system info.\n"
            "Edit to add your own endpoints.\n"
            "\"\"\"\n"
            "import json\n"
            "import os\n"
            "import platform\n"
            "from http.server import BaseHTTPRequestHandler, HTTPServer\n"
            "\n"
            "PORT = int(os.environ.get(\"PORT\", 8000))\n"
            "\n"
            "class Handler(BaseHTTPRequestHandler):\n"
            "    def do_GET(self):\n"
            "        if self.path == \"/\":\n"
            "            body = json.dumps({\n"
            "                \"name\": \"{project_name}\",\n"
            "                \"hostname\": platform.node(),\n"
            "                \"platform\": platform.platform(),\n"
            "            }).encode()\n"
            "            self.send_response(200)\n"
            "            self.send_header(\"Content-Type\", \"application/json\")\n"
            "            self.end_headers()\n"
            "            self.wfile.write(body)\n"
            "        else:\n"
            "            self.send_response(404)\n"
            "            self.end_headers()\n"
            "\n"
            "if __name__ == \"__main__\":\n"
            "    print(f\"Listening on 0.0.0.0:{PORT}\")\n"
            "    HTTPServer((\"0.0.0.0\", PORT), Handler).serve_forever()\n"
        ),
        "install.sh": (
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "\n"
            "if [ \"$EUID\" -ne 0 ]; then\n"
            "  echo \"Run with sudo: sudo ./install.sh\"\n"
            "  exit 1\n"
            "fi\n"
            "\n"
            "APP_DIR=$(pwd)\n"
            "SERVICE={project_slug}\n"
            "\n"
            "echo \"Installing $SERVICE...\"\n"
            "\n"
            "cat > /etc/systemd/system/$SERVICE.service <<EOF\n"
            "[Unit]\n"
            "Description={project_name}\n"
            "After=network.target\n"
            "\n"
            "[Service]\n"
            "Type=simple\n"
            "WorkingDirectory=$APP_DIR\n"
            "ExecStart=/usr/bin/python3 $APP_DIR/app.py\n"
            "Restart=always\n"
            "RestartSec=5\n"
            "User=$SUDO_USER\n"
            "\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n"
            "EOF\n"
            "\n"
            "systemctl daemon-reload\n"
            "systemctl enable $SERVICE\n"
            "systemctl start $SERVICE\n"
            "\n"
            "echo \"\"\n"
            "echo \"Installed. Check status with:\"\n"
            "echo \"  sudo systemctl status $SERVICE\"\n"
        ),
        ".gitignore": "__pycache__/\n*.pyc\n.env\n",
    },

}


def render_template(template_id: str, context: dict) -> dict[str, str]:
    """
    Render the files for a template with the given context.

    Uses simple string replacement instead of str.format() so that
    literal `{` and `}` characters in file content (YAML, code fences)
    don't need escaping.

    Context keys: project_name, project_slug, description
    """
    files = TEMPLATE_FILES.get(template_id)
    if not files:
        return {}

    rendered: dict[str, str] = {}
    for path, content in files.items():
        out = content
        for key, value in context.items():
            out = out.replace("{" + key + "}", str(value))
        rendered[path] = out
    return rendered
